CREATE DATABASE ecarteira;

\c;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    cpf VARCHAR(20) UNIQUE NOT NULL,
    password VARCHAR(50) NOT NULL
);